### PR TITLE
Add travis with autodeployment

### PR DESCRIPTION
**Pull request by jsvgoncalves**
Travis builds only to master (including PRs), testing the middleman
build. If the build doesn't come from a PR, then travis will also
deploy.

The sensitive data (keys, names, remotes..) is encrypted locally and
should be decrypted by travis (and never output into the logs)

Signed-off-by: Joao Goncalves <jsvgoncalves@redhat.com>

### CODE REVIEW

**Comment by jsvgoncalves** [comment]
@developercorey @luciddreamz

**Comment by developercorey** [comment]
Looks good to me, @luciddreamz do you have any comments?

**Comment by luciddreamz** [comment]
@developercorey @jsvgoncalves Looks good

**Comment by jsvgoncalves** [comment]
Merged as a026ba0be5cd67ea25f9aee7025277dfbae4ab49

**Pull request merged**
